import type { Metadata } from "next";
import LocalFont from "next/font/local";
import { Special_Elite } from "next/font/google";
import { ThemeProvider } from "next-themes";
import Header from "./components/header/header";
import Container from "./components/container/container";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import "./globals.css";

const specialEliteFont = Special_Elite({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
  variable: "--ff-special-elite",
  display: "swap",
});

const bespokeFont = LocalFont({
  src: [
    { path: "../public/fonts/BespokeSerif-Variable.woff2", style: "normal" },
    {
      path: "../public/fonts/BespokeSerif-VariableItalic.woff2",
      style: "italic",
    },
  ],
  variable: "--ff-bespoke",
  display: "swap",
});

const manropeFont = LocalFont({
  src: [{ path: "../public/fonts/Manrope-Variable.woff2", style: "normal" }],
  variable: "--ff-manrope",
  display: "swap",
});

const melodramaFont = LocalFont({
  src: [{ path: "../public/fonts/Melodrama-Variable.woff2", style: "normal" }],
  variable: "--ff-melodrama",
  display: "swap",
});

const satoshiFont = LocalFont({
  src: [
    { path: "../public/fonts/Satoshi-Variable.woff2", style: "normal" },
    { path: "../public/fonts/Satoshi-VariableItalic.woff2", style: "italic" },
  ],
  variable: "--ff-satoshi",
  display: "swap",
});

const tekoFont = LocalFont({
  src: [{ path: "../public/fonts/Teko-Variable.woff2", style: "normal" }],
  variable: "--ff-teko",
  display: "swap",
});

const nippoFont = LocalFont({
  src: [{ path: "../public/fonts/Nippo-Variable.woff2", style: "normal" }],
  variable: "--ff-nippo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function ThemeScript() {
  const themeScript = `
    (function() {
      const theme = localStorage.getItem('data-theme') || 'default';
      document.documentElement.setAttribute('data-theme', theme);
    })()
  `;

  return <script dangerouslySetInnerHTML={{ __html: themeScript }} />;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get session server-side to avoid flash in Header
  const headersList = await headers();
  const session = await auth.api.getSession({
    headers: headersList,
  });

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${specialEliteFont.variable} ${bespokeFont.variable} ${manropeFont.variable} ${melodramaFont.variable} ${satoshiFont.variable} ${tekoFont.variable} ${nippoFont.variable}`}
    >
      <head>
        <ThemeScript />
      </head>
      <body>
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="default"
          themes={["default", "typewriter", "floral", "sprawl", "monitor"]}
        >
          <Header initialSession={session} />
          <Container classes="main-content" tag="main">
            {children}
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
